### ISSUE TITLE
How to restrict a special commands for admins only?

### ISSUE THREAD

**Issue by Spidersouris** [SteamingMutt/WildBeast#103]
Hey!

We installed the bot on our Discord server and we love it, thanks a lot.

I'd like to know if it was possible to restrict ++skip for admins only, because our members do it every time they wanna listen to their music.

Thanks a lot!

**Comment by SteamingMutt** [comment]
Edit `commands/music.js`, at line 41 there's a `level` property, if you set that to 5 or higher, only master users can execute that command
