### ISSUE TITLE
Request not adding video from YouTube to the playlist

### ISSUE THREAD

**Issue by yugiko** [SteamingMutt/WildBeast#105]
Hey, not sure since when this problem is present, just tried it today, but with the usual "++request last part" after the ?v=[_this part_]" neither with the whole YouTube link it's adding it to the playlist.
Either giving the error message "That's not how you do it, you need to enter a link to a file for me to play." when just using the last part of the URL or "I couldn't add that to the playlist." when using the complete URL.
I think it's the same when using ++queue instead of ++request

**Comment by SteamingMutt** [comment]
You need to use full URLs since 3.0.0-beta-5, so like `++request https://www.youtube.com/watch?v=_cB3HXVvm0g`

**Comment by yugiko** [comment]
"neither with the whole YouTube link it's adding it to the playlist." Second part of the first sentence. It just gives the message "I couldn't add that to the playlist". Would you suggest kicking the bot from the server and Re-inviting it, to try if that would fix it?

**Comment by SteamingMutt** [comment]
Did you add a Google key in the config? That's required now for YouTube streaming

**Comment by yugiko** [comment]
I don't think we did anything with other than inviting it on the server from this website: https://www.carbonitex.net/Discord/bots
Gonna get through the readme as soon as I get home and follow the steps there and take a look if it's working, thanks for the fast response nonetheless!
