### ISSUE TITLE
Request Issue

### ISSUE THREAD

**Issue by Jakosaur** [SteamingMutt/WildBeast#107]
I have recently setup WildBeast onto my Raspberry Pi and everything is working except from the !request command.

When I request a song, in the console it shows 
![image](https://cloud.githubusercontent.com/assets/20144356/16358544/c027b6cc-3b0d-11e6-9a87-0a57f4157b61.png)

The bot says "I couldn't add that to the playlist." and then deletes the message it just sent.

**Comment by SteamingMutt** [comment]
Try updating the youtube-dl module, run `npm rebuild youtube-dl` in the console and try again.

**Comment by zaza7** [comment]
@SteamingMutt IIRC you need to compile ffmpeg for the rPI and it doesn't compile with HTTPS support unless you get a lot of devel libs and some compile options to make it do so.

**Comment by SteamingMutt** [comment]
True, but if a problem with FFmpeg arose from this, it should just add it to the playlist and fail to play it back

**Comment by Jakosaur** [comment]
Sorry for the late reply. I tried updating youtube-dl.
Now the wait music doesn't even play. When I request a youtube video it says that it has been added to the playlist, then it says the song has now ended and then says the playlist has finished and leaves the voice channel.

Thanks for taking your time to help me.

**Comment by SteamingMutt** [comment]
Aight, that's a FFmpeg problem, refer to https://github.com/SteamingMutt/WildBeast/issues/107#issuecomment-229255568
