### ISSUE TITLE
prefix issue.

### ISSUE THREAD

**Issue by zaza7** [SteamingMutt/WildBeast#14]
If prefix is set to something like `++` or `**` the .search() function will turn it onto a regular expression causing a crash.  Doing the following it appears to not break when those types of prefixes are used and also works when it's set to mention.

Replacing
```
if (msg.content.search(prefix) === 0) {
```
for
```
if (msg.content.includes(prefix)) {
```

**Comment by SteamingMutt** [comment]
:+1:
