### ISSUE TITLE
Custom timeout

### ISSUE THREAD

**Issue by heewphan** [SteamingMutt/WildBeast#18]
Had this idea but wasn't able to pull it off. 

Have a custom timeout function so it could send different timeout messages or execute a function for a certain command. Also if possible, a counter so if a command is getting spammed while still within timeout, the user can get kicked or something. 

Not really game changing but just something that could be fun to implement.

**Comment by SteamingMutt** [comment]
I'll throw your idea into the group

**Comment by SteamingMutt** [comment]
Sorta live right now in 3.0.0
