### ISSUE TITLE
[3.0.0] Trivia

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/WildBeast#19]
Make a trivia command that will ask the users in the server a question and they have to answer asap to score points.

For added effect, make users first say *Buzz* before they can answer, giving them 5 seconds of solo right to answer the question before reopening the answer window.

**Comment by Rekkisomo** [comment]
Maybe add a 30-60 seconds before skipping to a next question. 👌

**Comment by Stawln** [comment]
i love how this dead
