### ISSUE TITLE
Deviant Art

### ISSUE THREAD

**Issue by Hendrik-Sama** [SteamingMutt/WildBeast#7]
Have you ever found yourself thinking: Why? O why can't I just use DougleyBot to search the weird stuff on Deviant Art? Well, I have an answer for you! And it's completely free. I think. https://www.deviantart.com/developers/rss

**Comment by SteamingMutt** [comment]
Utilizes RSS, isn't too hard to do imho

**Comment by Perpetucake** [comment]
Eww RSS in javascript, not this again
oh look JSON to save the day! https://www.deviantart.com/developers/oembed

**Comment by SteamingMutt** [comment]
The oEmbed API enables the script to display content from DeviantArt, however, the RSS enables fetching content from DeviantArt, I don't think oEmbed has the ability to search for Deviations.
