### ISSUE TITLE
Help sent via DM - Not possible if token_mode is true

### ISSUE THREAD

**Issue by palmtree5** [SteamingMutt/WildBeast#78]
This should probably be disabled (and command help or the help command output should be sent to the channel) if token_mode is set to true in the config seeing as it seems that bot accounts can't send PMs

**Comment by cernodile** [comment]
I'd like to say against one thing in your message, it only can't send messages to people who haven't pm'd the bot first.

**Comment by palmtree5** [comment]
Thanks for pointing that out. I'm closing this then
